version: "3.3"
services:
  gitlab:
    image: 'gitlab/gitlab-ce:latest'
    restart: always
    hostname: 'mondher.gitlab.com'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'https://mondher.gitlab.com'
    ports:
      - '80:80'
      - '443:443'
      - '22:22'
    volumes:
      - '~/gitlab/config:/etc/gitlab'
      - '~/gitlab/logs:/var/log/gitlab'
      - '~/gitlab/data:/var/opt/gitlab'
    networks:
      gitlab:
        ipv4_address: "10.17.17.17"

networks:
  gitlab:
    ipam:
      driver: default
      config:
        - subnet: 10.17.17.0/24
      

