version: "3.3"
services:
  gitlab:
    image: 'gitlab/gitlab-ce:latest'
    restart: always
    hostname: 'example.gitlab.com'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'https://example.gitlab.com'
    ports:
      - '80:80'
      - '443:443'
      - '22:22'
    volumes:
      - '~/gitlab/config:/etc/gitlab'
      - '~/gitlab/logs:/var/log/gitlab'
      - '~/gitlab/data:/var/opt/gitlab'
    networks:
      gitlab:
<<<<<<< HEAD
        ipv4_address: "__________"
>>>>>>> refs/remotes/origin/main

networks:
  gitlab:
    ipam:
      driver: default
      config:
<<<<<<< HEAD
        - subnet: ___________
>>>>>>> refs/remotes/origin/main
      

