services:
  gitlab:
    image: 'gitlab/gitlab-ce:latest'
    restart: unless-stopped
    hostname: 'mondher.gitlab.com'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'https://mondher.gitlab.com'
    ports:
      - '80:80'
      - '443:443'
      - '22:22'
    volumes:
      - '~/gitlab/config:/etc/gitlab'
      - '~/gitlab/logs:/var/log/gitlab'
      - '~/gitlab/data:/var/opt/gitlab'
    networks:
      - gitlab

  gitlab-runner:
    image: 'gitlab/gitlab-runner:latest'
    depends_on:
      - gitlab
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
      - '~/gitlab/config-runner:/etc/gitlab-runner'
    ports:
      - '8093:8093'
    restart: unless-stopped
    networks:
      - gitlab

networks:
  gitlab:
      

